### ISSUE TITLE
Support for code tracing?

### ISSUE THREAD

**Issue by xixilive** [jrsearles/SandBoxr#1]
Sandboxr is a awesome project, and I'm researching the code tracing feature of this library. 
Could you expose any advice about this topic?

**Comment by jrsearles** [comment]
Thanks for your comments. I haven't done much work for supporting tracing, though i'm using generators to step through the ast nodes so it should be feasible to provide a stepping mechanism. It's something i plan on exploring at some point.

What kind of tracing are you hoping to do?

**Comment by xixilive** [comment]
purpose to interactive debug, syntax highlight, etc :smile:

**Comment by jrsearles** [comment]
Sounds interesting. My thoughts were as part of the stepping mechanism i can return the current ast node being evaluated, which would give you the position (assuming that's part of the ast), the current scope which would give you all the variables and their values (and the parent, so you could view the scope all the way to global), and the result of the last node evaluated. Do you think that would be beneficial to you?

**Comment by xixilive** [comment]
GOT IT, THKS SO MUCH!
