### ISSUE TITLE
Example of async execution in Sandbox.prototype.execute()

### ISSUE THREAD

**Issue by evan-coygo** [jrsearles/SandBoxr#11]
It would be great to have some documentation or examples around how to execute code asynchronously inside a sandbox and get the result. The README for mentions:

> `SandBox.prototype.execute(env: Environment?): ObjectType|Promise` - ...... The function will return the result of the execution. If async code is executed a Promise will be returned that will resolve to the execution result.

When I try to define a Promise within the ast passed into the sandbox I get an error "Promise is not defined", so I'm confused how to implement that.

Thanks for the help!

**Comment by jrsearles** [comment]
There is an example in the readme:

```js
var env = SandBoxr.createEnvironment();

var fooFunc = env.objectFactory.createFunction(function () {
	return $.get("/some/server/request").then(function (res) {
		// remember that anything you pass back needs to be wrapped
		// todo: more docs on object factory
		return env.objectFactory.createPrimitive(res.value);
	});
});

var foo = env.createVariable("o");
foo.setValue(fooFunc);
```

You run the async code as normal, but when you resolve the promise, return a wrapped object/primitive.
