### ISSUE TITLE
how about separated or isolated builds for ES5/ES6?

### ISSUE THREAD

**Issue by xixilive** [jrsearles/SandBoxr#4]
Sometimes, I need ES5 features only, and so I want to remove ES6-related features from build to decrease target package size.
For this purpose, I must to modify the source-code in current version. 
Is there a better customization strategy?

**Comment by jrsearles** [comment]
Thanks for this issue. I've been considering ways i might break this up. I could make two separate builds, though i don't think it would end up saving much on the package size. 

How do you consume this currently? Bower? NPM? or just copy the distributed files?

**Comment by xixilive** [comment]
Thanks for your response!
I consume Sandboxr with npm in my project, and package it with webpack.

---

Package size of [my fork](https://github.com/xixilive/SandBoxr/tree/JIMU) with ES6 and without ES6 + babel-runtime:
- **with** ES6 and babel-runtime
  compiled: 649K
  minified: 328K
- **without** ES6 and runtime
  compiled: 464K
  minified: 235K

Minified version saves about 100K.
