### ISSUE TITLE
The SandBoxr.createEnvironment args was inconsistent with Environment constructor

### ISSUE THREAD

**Issue by xixilive** [jrsearles/SandBoxr#5]
Here is the createEnvironment function in `/index.js` [source L12](https://github.com/jrsearles/SandBoxr/blob/2956a7e608456b0159b3e5e502e271357a6125ee/index.js#L12):

```
// notice the options argument
export function createEnvironment (options) {
  return new Environment(options);
}
```

And the Environment constructor in `/src/env/index.js` [source L29](https://github.com/jrsearles/SandBoxr/blob/2956a7e608456b0159b3e5e502e271357a6125ee/src/env/index.js#L29):

```
// constructor with empty-arguments declaration
export function Environment () {}
```

**Comment by jrsearles** [comment]
Good catch. I looked through the history and the Environment constructor never accepted options so it looks like this was a mistake in the createEnvironment method. I did an update to remove the options from that method.

It might be nice to have it take options and init the environment (that's what accepts options), but this would be a breaking change. I'm open to that if it'd be useful for you.
