### ISSUE TITLE
Environment throwing error on undefined `scope` in browser & node

### ISSUE THREAD

**Issue by konsumer** [jrsearles/SandBoxr#7]
I made a [test codepen](http://codepen.io/konsumer/pen/jBRVPQ?editors=0010) to illustrate the issue I am having of not being able to set environment.

```js
const ast = acorn.parse(`a === 99`)
const env = SandBoxr.createEnvironment()
const a = env.createVariable('a')
a.setValue(env.objectFactory.createPrimitive(99))
const sandbox = SandBoxr.create(ast)
const result = sandbox.execute(env)
const nativeValue = result.toNative()
expect(nativeValue).to.be.ok
```

In node, I get this error:
```
TypeError: Cannot read property 'scope' of undefined
      at Environment.createVariable (node_modules/sandboxr/dist/sandboxr.js:3936:29)
      at index.js:9:22
      at Context.it (test/test.js:25:14)
```

Am I doing something wrong?

**Comment by konsumer** [comment]
node_modules/sandboxr/dist/sandboxr.js:3936 looks like this:
```js
  createVariable: function (key, kind) {
    kind = kind ? kind.toLowerCase() : "var";
    var attr = declareKinds[kind];
    var scope = this.current.scope;
```

**Comment by jrsearles** [comment]
You need to call `env.init()` before using the environment. It looks like the example in the readme was missing that call. Sorry about that.

For more examples of customizations, these tests give some examples:
https://github.com/jrsearles/SandBoxr/blob/master/test/api.tests.js

**Comment by konsumer** [comment]
Aha! Works [like a charm](http://codepen.io/konsumer/pen/evoBjp). Thanks!

**Comment by konsumer** [comment]
As a related sidenote, is there a simple way to set the env with a JSON-representable object?

I tried this:

```js
const astToFunc = ast => {
  const sandbox = SandBoxr.create(ast)
  return (row) => {
    const env = SandBoxr.createEnvironment()
    env.init()
    Object.keys(row).forEach(k => {
      const v = env.createVariable(k)
      v.setValue(env.objectFactory.createPrimitive(row[k]))
    })
    return sandbox.execute(env).toNative()
  }
}
```

which works great for an object with only primitive values, but throws `Error: Not a primitive: [object Object]` on an object like this: `{obj: {cool: false}}`

**Comment by konsumer** [comment]
Ah, I got it. I just need to [inject the JSON](http://codepen.io/konsumer/pen/zZXyMb):

```js
const runWithEnv = (code, row={}) => {
  const wrappedCode=`
    const f = row => (${code})
    f(${JSON.stringify(row)})
  `
  const ast = acorn.parse(wrappedCode)
  const sandbox = SandBoxr.create(ast)
  const result = sandbox.execute()
  return result.toNative()
}

expect(runWithEnv(`row.person.name === 'David'`, {person: {name: 'David'}})).to.be.ok
expect(runWithEnv(`row.person.name === 'Leander'`, {person: {name: 'David'}})).to.not.be.ok
```

**Comment by jrsearles** [comment]
Yeah - that works. There's not currently a simple way to create objects, but it is possible. Something like:

```javascript
    let instance = env.objectFactory.createObject();
    instance.defineProperty("foo", { value: env.objectFactory.createPrimitive(true) });
    return instance;
```

It would get tedious quick with a deep object. It wouldn't be hard to add a wrapper function to build up an object if that would be useful though.
